package seminar1.homeWork.model;

public enum Commands {
    SEND_TEXT_TO_SERVER,
    SEND_CONNECT_TO_SERVER,
    SEND_DISCONNECT_TO_SERVER,
    ADD_TEXT_TO_CLIENT,
    SEND_CHANGE_STATUS,
    ACCEPT_DISCONNECT_FROM_SERVER,
    ACCEPT_CONNECT_FROM_SERVER,
    UPDATE_MESSAGES,
    CLOSE_SERVER
}
